#!/usr/bin/env bash
#
# launch-wizard.sh — interactive deployment wizard for
# Dynamic Image Transformation for Google Cloud CDN.
#
# Counterpart of the AWS "Launch Stack" CloudFormation experience: prompts for
# the same parameter set as the CFN template, then drives the Terraform module
# in ../terraform so both deployment paths produce identical resources.
#
# Usage:
#   ./launch-wizard.sh             interactive deploy
#   ./launch-wizard.sh --dry-run   interactive, stop after `terraform plan`
#   ./launch-wizard.sh --destroy   tear everything down (uses saved tfvars)
#
# Requirements: gcloud (authenticated), terraform >= 1.5. Designed to run in
# Cloud Shell (see README.md for the Open-in-Cloud-Shell button) or on any
# machine with ADC set up.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="${SCRIPT_DIR}/../terraform"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
TFVARS_FILE="${TF_DIR}/wizard.auto.tfvars"

MODE="apply"
case "${1:-}" in
  --destroy) MODE="destroy" ;;
  --dry-run) MODE="plan" ;;
  "") ;;
  *)
    echo "Unknown option: $1" >&2
    echo "Usage: $0 [--dry-run|--destroy]" >&2
    exit 1
    ;;
esac

# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

say()  { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33mWARNING: %s\033[0m\n' "$*" >&2; }
die()  { printf '\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

# ask VAR "prompt" "default" "validator"
# Validators: yesno | nonempty | domain | region | bool | any
ask() {
  local var="$1" prompt="$2" default="$3" validator="${4:-any}" value
  while true; do
    read -r -p "${prompt} [${default}]: " value
    value="${value:-$default}"
    case "$validator" in
      yesno)
        [[ "$value" == "Yes" || "$value" == "No" ]] && break
        echo "  Please answer exactly Yes or No." ;;
      bool)
        [[ "$value" == "true" || "$value" == "false" ]] && break
        echo "  Please answer true or false." ;;
      nonempty)
        [[ -n "$value" ]] && break
        echo "  A value is required." ;;
      domain)
        [[ "$value" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$ ]] && break
        echo "  Not a valid domain name (e.g. img.example.com)." ;;
      region)
        [[ "$value" =~ ^[a-z]+-[a-z]+[0-9]$ ]] && break
        echo "  Not a valid GCP region (e.g. asia-southeast1)." ;;
      any)
        break ;;
    esac
  done
  printf -v "$var" '%s' "$value"
}

check_dependencies() {
  say "Checking dependencies"
  command -v gcloud >/dev/null 2>&1 || die "gcloud CLI not found. Install the Google Cloud SDK first."
  command -v terraform >/dev/null 2>&1 || die "terraform not found. Install Terraform >= 1.5 first."
  gcloud auth list --filter=status:ACTIVE --format='value(account)' | grep -q . \
    || die "No active gcloud account. Run: gcloud auth login && gcloud auth application-default login"
  echo "  gcloud:    $(gcloud version --format='value(\"Google Cloud SDK\")' 2>/dev/null || gcloud version | head -1)"
  echo "  terraform: $(terraform version | head -1)"
}

enable_apis() {
  say "Enabling required APIs on ${PROJECT_ID} (no-op if already enabled)"
  gcloud services enable \
    run.googleapis.com \
    compute.googleapis.com \
    cloudbuild.googleapis.com \
    artifactregistry.googleapis.com \
    secretmanager.googleapis.com \
    vision.googleapis.com \
    storage.googleapis.com \
    --project "${PROJECT_ID}"
}

build_image() {
  say "Building the image handler container with Cloud Build"
  if ! gcloud artifacts repositories describe dit \
      --location "${REGION}" --project "${PROJECT_ID}" >/dev/null 2>&1; then
    echo "  Creating Artifact Registry repository 'dit'..."
    gcloud artifacts repositories create dit \
      --repository-format=docker \
      --location "${REGION}" \
      --project "${PROJECT_ID}" \
      --description "Dynamic Image Transformation images"
  fi
  gcloud builds submit "${REPO_ROOT}/source/image-handler" \
    --tag "${IMAGE}" \
    --project "${PROJECT_ID}"
}

write_tfvars() {
  say "Writing ${TFVARS_FILE}"
  cat > "${TFVARS_FILE}" <<EOF
# Generated by launch-wizard.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not edit
# by hand while the wizard manages this deployment.
project_id                    = "${PROJECT_ID}"
region                        = "${REGION}"
image                         = "${IMAGE}"
domain                        = "${DOMAIN}"
enable_http                   = ${ENABLE_HTTP}
deploy_demo_ui                = ${DEPLOY_DEMO_UI}
source_buckets                = "${SOURCE_BUCKETS}"
cors_enabled                  = "${CORS_ENABLED}"
cors_origin                   = "${CORS_ORIGIN}"
auto_webp                     = "${AUTO_WEBP}"
enable_signature              = "${ENABLE_SIGNATURE}"
enable_default_fallback_image = "${ENABLE_FALLBACK}"
fallback_image_bucket         = "${FALLBACK_BUCKET}"
fallback_image_key            = "${FALLBACK_KEY}"
compat_aws_limits             = "${COMPAT_AWS_LIMITS}"
EOF
}

run_terraform() {
  say "Running Terraform (${MODE})"
  terraform -chdir="${TF_DIR}" init -input=false
  if [[ "${MODE}" == "plan" ]]; then
    terraform -chdir="${TF_DIR}" plan -input=false
    say "Dry run complete — no resources were created."
    return
  fi
  terraform -chdir="${TF_DIR}" apply -input=false -auto-approve
}

print_next_steps() {
  local lb_ip
  lb_ip="$(terraform -chdir="${TF_DIR}" output -raw lb_ip)"
  say "Deployment complete"
  terraform -chdir="${TF_DIR}" output
  cat <<EOF

Next steps
----------
1. DNS: create an A record for ${DOMAIN} pointing to ${lb_ip}.
2. Certificate: the Google-managed certificate activates only after DNS
   resolves to the IP above (typically 15-60 min). Check with:
     gcloud compute ssl-certificates list --project ${PROJECT_ID}
3. Until HTTPS is active you can test over plain HTTP (enable_http=true):
     curl -H "Host: ${DOMAIN}" http://${lb_ip}/<base64-request>
4. Upload source images:
     gsutil cp my.jpg gs://${PROJECT_ID}-dit-source/
5. Run the e2e suite:
     BASE_URL=https://${DOMAIN} ${REPO_ROOT}/deployment/run-e2e-tests.sh
EOF
  if [[ "${ENABLE_SIGNATURE}" == "Yes" ]]; then
    cat <<EOF
6. IMPORTANT: signatures are enabled but the secret still holds the
   CHANGE_ME placeholder. Rotate it now:
     printf '{"signatureKey":"%s"}' "\$(openssl rand -hex 32)" | \\
       gcloud secrets versions add dit-signature-secret --data-file=- --project ${PROJECT_ID}
EOF
  fi
}

# ---------------------------------------------------------------------------
# destroy path
# ---------------------------------------------------------------------------

if [[ "${MODE}" == "destroy" ]]; then
  check_dependencies
  [[ -f "${TFVARS_FILE}" ]] || warn "No ${TFVARS_FILE} found; destroy will use variable defaults."
  say "Destroying the deployment"
  read -r -p "Type 'destroy' to confirm: " confirm
  [[ "${confirm}" == "destroy" ]] || die "Aborted."
  terraform -chdir="${TF_DIR}" init -input=false
  terraform -chdir="${TF_DIR}" destroy -input=false
  say "Destroy complete. The Artifact Registry repo and built images are kept; remove them with:
  gcloud artifacts repositories delete dit --location <region> --project <project>"
  exit 0
fi

# ---------------------------------------------------------------------------
# parameter collection (mirrors the CloudFormation parameter table)
# ---------------------------------------------------------------------------

cat <<'EOF'
+--------------------------------------------------------------------+
|   Dynamic Image Transformation for Google Cloud CDN — Launch Wizard |
|   (parameters mirror the AWS CloudFormation template)               |
+--------------------------------------------------------------------+
EOF

DEFAULT_PROJECT="$(gcloud config get-value project 2>/dev/null || true)"
ask PROJECT_ID       "GCP project ID"                                    "${DEFAULT_PROJECT:-helloworld-334009}" nonempty
ask REGION           "Region"                                            "asia-southeast1" region
ask DOMAIN           "Domain for the HTTPS endpoint"                     "img.googledemo.com" domain
ask SOURCE_BUCKETS   "SourceBuckets (comma-separated, first = default)"  "${PROJECT_ID}-dit-source" nonempty
ask CORS_ENABLED     "CorsEnabled (Yes/No)"                              "No" yesno
CORS_ORIGIN="*"
if [[ "${CORS_ENABLED}" == "Yes" ]]; then
  ask CORS_ORIGIN    "CorsOrigin"                                        "*" nonempty
fi
ask AUTO_WEBP        "AutoWebP (Yes/No)"                                 "Yes" yesno
ask ENABLE_SIGNATURE "EnableSignature (Yes/No)"                          "No" yesno
ask ENABLE_FALLBACK  "EnableDefaultFallbackImage (Yes/No)"               "No" yesno
FALLBACK_BUCKET=""; FALLBACK_KEY=""
if [[ "${ENABLE_FALLBACK}" == "Yes" ]]; then
  ask FALLBACK_BUCKET "FallbackImageBucket"                              "${PROJECT_ID}-dit-source" nonempty
  ask FALLBACK_KEY    "FallbackImageKey"                                 "fallback.png" nonempty
fi
ask DEPLOY_DEMO_UI    "DeployDemoUI (true/false)"                        "true" bool
ask ENABLE_HTTP       "Keep plain HTTP :80 open for testing (true/false)" "true" bool
ask COMPAT_AWS_LIMITS "CompatAwsLimits — replicate 6MB/413 (Yes/No)"     "No" yesno
ask IMAGE_TAG         "Image tag to build"                               "latest" nonempty

IMAGE="${REGION}-docker.pkg.dev/${PROJECT_ID}/dit/image-handler:${IMAGE_TAG}"

cat <<EOF

Summary
-------
  Project:            ${PROJECT_ID}
  Region:             ${REGION}
  Domain:             ${DOMAIN}
  Image:              ${IMAGE}
  SourceBuckets:      ${SOURCE_BUCKETS}
  CorsEnabled:        ${CORS_ENABLED} (origin: ${CORS_ORIGIN})
  AutoWebP:           ${AUTO_WEBP}
  EnableSignature:    ${ENABLE_SIGNATURE}
  Fallback image:     ${ENABLE_FALLBACK} (${FALLBACK_BUCKET}/${FALLBACK_KEY})
  DeployDemoUI:       ${DEPLOY_DEMO_UI}
  HTTP :80 enabled:   ${ENABLE_HTTP}
  CompatAwsLimits:    ${COMPAT_AWS_LIMITS}
  Mode:               ${MODE}
EOF

read -r -p "Proceed? (y/N): " go
[[ "${go}" == "y" || "${go}" == "Y" ]] || die "Aborted."

check_dependencies
enable_apis
if [[ "${MODE}" == "apply" ]]; then
  build_image
else
  warn "Dry run: skipping the container build; the plan assumes ${IMAGE} exists."
fi
write_tfvars
run_terraform
if [[ "${MODE}" == "apply" ]]; then
  print_next_steps
fi
